spring:
  batch:
    job:
      name: ${job.name:helloWorldJob}
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/Batch_25_06?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ""
  jpa:
    show-sql: true
